PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX rpubl: <http://rinfo.lagrummet.se/ns/2008/11/rinfo/publ#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

CONSTRUCT {
  <%(uri)s> dcterms:isReferencedBy ?referer .
  ?referer ?p ?o .
  ?o rdfs:label ?olabel .
  <%(uri)s> ?rp ?ro .
}
WHERE
{
  {
    <%(uri)s> ?rp ?ro .
  } UNION {
    ?referer dcterms:references <%(uri)s> .
    ?referer ?p ?o .
    } UNION {
      ?o rdfs:label ?olabel .
}
}

