PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX rpubl: <http://rinfo.lagrummet.se/ns/2008/11/rinfo/publ#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX bibo: <http://purl.org/ontology/bibo/>
PREFIX olo: <http://purl.org/ontology/olo/core#>


CONSTRUCT {
  ?target dcterms:isReferencedBy ?referer .
  ?referer ?p ?o .
}
WHERE
{
      ?referer dcterms:references ?target .
      ?referer ?p ?o .
      FILTER(STRSTARTS(STR(?target), "%(uri)s"))

}

