PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX rinfoex: <http://lagen.nu/terms#>

SELECT DISTINCT ?lagrum ?kommentar ?prop ?desc
WHERE  {
  {
    ?kommentar rinfoex:kommentarTill ?lagrum;
               dcterms:description ?desc;
               dcterms:isPartOf+ ?propuri .
    ?propuri dcterms:identifier ?prop .
    FILTER(STRSTARTS(STR(?lagrum), "%(uri)s"))
  } UNION {
    ?kommentar rinfoex:kommentarTill ?lagrum;
               dcterms:description ?desc;
               dcterms:isPartOf+ ?propuri .
    ?propuri dcterms:identifier ?prop .
    FILTER(STRSTARTS(STR(?lagrum), "%(tempuri)s"))
  }
} 
