PREFIX rdf:<http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX dcterms:<http://purl.org/dc/terms/>
PREFIX rpubl:<http://rinfo.lagrummet.se/ns/2008/11/rinfo/publ#>

SELECT DISTINCT ?change ?changetype ?id ?lagrum ?prop ?propid ?proptitle
WHERE {
    ?change (rpubl:ersatter|rpubl:upphaver|rpubl:inforsI)  ?lagrum;
	    ?changetype ?lagrum;
            dcterms:identifier ?id;
            rpubl:forarbete ?prop .
    ?prop rdf:type rpubl:Proposition . 
    OPTIONAL {
      ?prop dcterms:identifier ?propid;
            dcterms:title ?proptitle .
    }
    FILTER(STRSTARTS(STR(?lagrum), "%(uri)s"))
}
