# Maybe should be called describe.rq instead?
PREFIX dcterms: <http://purl.org/dc/terms/>

CONSTRUCT
{
   ?part dcterms:isReferencedBy ?s .
   ?s ?p ?o .
}
WHERE 
{
  ?s ?p ?o .
  {
    ?s dcterms:isPartOf* <%(uri)s> .
  }
  UNION
  {
    ?part dcterms:isPartOf* <%(uri)s> .
    ?s dcterms:references ?part .
  }
}
