"""ECHR case-law citations in Swedish legal text, as `Ref` spans -- the
EMDRATTSFALL half of the citation engine.

Swedish courts, förarbeten and myndigheter cite Strasbourg case law by party
names in Swedish spelling -- "Osman mot Förenade kungariket", "Centrum för
Rättvisa mot Sverige, p. 256" -- and by application number ("ansökan nr
23452/94"). Neither form is a grammar production: the applicant side is an
open vocabulary of 37,000+ held case names, so this module is a matcher over
the committed snapshot (`hudoc/data/casenames.json`, generated by
hudoc.casenames from the held records) joined through the hand-edited Swedish
respondent names (`respondents_sv.json`). The same two-stage shape as
hudoc.citations, which does this for the English surface inside the hudoc
corpus itself: a cheap anchor proposes (" mot " + a known state name; "nr" +
an application-number shape), the snapshot disposes.

Disambiguation is hudoc.citations' rule ported verbatim: a date printed
beside the citation wins; else the sole judgment; several candidates and no
date is a chamber/Grand-Chamber guess and stays unlinked (rule:fail-fast).
"""

import functools
import re

# `lagrum` is imported as a module, not `from .lagrum import Ref`: lagrum
# imports this module for its `spans`, so only the module form survives the
# cycle (the attribute is read at call time, when lagrum is fully loaded)
from . import datasets, lagrum
from .util import MONTHS, normalize_space

PREDICATE = "dcterms:references"
ECHR_LOCAL = "dom/echr/"

# how far back an applicant's name may start before " mot ", and how far
# forward a respondent may reach; past these the words are the sentence's,
# not the citation's (hudoc.citations' windows)
APPLICANT_WINDOW = 60
RESPONDENT_WINDOW = 45

RE_MOT = re.compile(r"\smot\s")
RE_SERIAL_AFTER = re.compile(r"\s*\((?:nr|no\.?)\s*(\d+)\)", re.I)
# "ansökan nr 23452/94", "ansökningarna nr 3455/05 och 28901/95",
# "klagomål nr 62332/00" -- the marker word is required: a bare
# "nr \d+/\d+" is how riksmöten and löpnummer read too
RE_APPNO_LIST = re.compile(
    r"\b(?:ansökan|ansökningarna|ansökningar|klagomålen|klagomål)\s+"
    r"nr\.?\s*(\d{3,5}/\d{2}(?:(?:\s*(?:,|och)\s*)\d{3,5}/\d{2})*)")
RE_APPNO = re.compile(r"\d{3,5}/\d{2}")
# a Swedish date within the citation's own apparatus, never past a sentence
# boundary: "…, dom den 28 oktober 1998" after it, or "Europadomstolens dom
# den 4 mars 2004, M.C. mot Bulgarien" before it
_DATE = r"\bden\s+(\d{1,2})\s+(%s)\s+(\d{4})" % "|".join(MONTHS)
RE_DATE_AFTER = re.compile(r"[^.;()]{0,60}?" + _DATE)
RE_DATE_BEFORE = re.compile(_DATE + r"[^.;()]{0,60}$")


def fold_party_name(name):
    """One party name, comparable across a title's caps and a citation's mixed
    case: casefolded, determiners dropped, punctuation-insensitive. The snapshot
    keys here and the hudoc citation matcher are both built with it, so it lives
    on this side -- lib never imports a vertical (rule:lib-never-imports-vertical)."""
    name = normalize_space(name).casefold().replace("the ", " ")
    return re.sub(r"[^\w]+", " ", name).strip()


@functools.cache
def _index():
    """The committed snapshot keyed for both matchers: ``by_name[(applicant,
    respondent, serial)]`` and ``by_no[appno]`` -> [(kind, date, itemid)],
    plus the Swedish respondent vocabulary (Swedish spelling, casefolded ->
    the snapshot's own respondent keys)."""
    emd = datasets.load_emd_cases()
    by_name = {}
    for key, entries in emd["cases"].items():
        applicant, respondent, serial = key.split("|")
        by_name[(applicant, respondent, serial)] = entries
    respondents_sv = {
        sv.casefold(): keys
        for sv, keys in datasets.load_emd_respondents().items()}
    return by_name, emd["appnos"], respondents_sv


def pick(candidates, near_date, *, judgment_key, exclude=None):
    """The one document a citation means, or None. An exact nearby date wins;
    else the sole judgment; else the sole document. Several candidates and no
    date is a chamber/Grand-Chamber guess, and stays unlinked
    (rule:fail-fast).

    A candidate is ``(kind, date, itemid)``. `judgment_key` is the kind value
    that reads as "judgment" on the caller's side: this module matches the
    committed snapshot, which abbreviates it to "j", while hudoc.citations
    matches its own records, which spell it "judgment". `exclude` is an
    itemid the citation cannot mean -- hudoc drops the citing document
    itself, whose own application number and case name name *this* case."""
    if exclude is not None:
        candidates = [c for c in candidates if c[2] != exclude]
    if near_date:
        dated = [c for c in candidates if c[1] == near_date]
        if len(dated) == 1:
            return dated[0]
    judgments = [c for c in candidates if c[0] == judgment_key]
    if len(judgments) == 1:
        return judgments[0]
    if not judgments and len(candidates) == 1:
        return candidates[0]
    return None


def _near_date(text, start, end):
    m = RE_DATE_AFTER.match(text, end) or RE_DATE_BEFORE.search(text[:start])
    if not m:
        return None
    return "%04d-%02d-%02d" % (int(m.group(3)),
                               MONTHS[m.group(2).lower()],
                               int(m.group(1)))


def _is_year_pair(no):
    """"1994/95" reads as an application number's shape but is a riksmöte."""
    first, second = no.split("/")
    return (len(first) == 4 and 1800 <= int(first) <= 2099
            and int(second) == (int(first) + 1) % 100)


def _appno_refs(text, base, by_no):
    out = []
    for m in RE_APPNO_LIST.finditer(text):
        for no in RE_APPNO.finditer(m.group(1)):
            if _is_year_pair(no.group(0)):
                continue
            picked = pick(by_no.get(no.group(0), ()),
                          _near_date(text, m.start(), m.end()),
                          judgment_key="j")
            if picked:
                start = m.start(1) + no.start()
                out.append((start, start + len(no.group(0)),
                            base + ECHR_LOCAL + picked[2]))
    return out


def _name_refs(text, base, by_name, respondents_sv):
    out, consumed = [], 0
    for m in RE_MOT.finditer(text):
        if m.start() < consumed:
            continue
        # respondent: the longest Swedish state name the following text
        # spells (its own casing; citations write "Förenade kungariket")
        after = text[m.end():m.end() + RESPONDENT_WINDOW]
        resp = next((cut for cut in range(len(after), 0, -1)
                     if after[:cut].casefold() in respondents_sv
                     and (cut == len(after) or not after[cut].isalnum())),
                    None)
        if resp is None:
            continue
        resp_keys = respondents_sv[after[:resp].casefold()]
        serial = RE_SERIAL_AFTER.match(text, m.end() + resp)
        # applicant: the longest word-boundary suffix before " mot " that,
        # with this respondent, is a held case
        before = text[max(0, m.start() - APPLICANT_WINDOW):m.start()]
        found = None
        for cut in [0] + [w.end() for w in re.finditer(r"[\s(]", before)]:
            if not before[cut:].strip():
                continue
            for rk in resp_keys:
                key = (fold_party_name(before[cut:]), rk,
                       serial.group(1) if serial else "")
                if key in by_name:
                    found = (cut, key)
                    break
            if found:
                break
        if not found:
            continue
        cut, key = found
        end = serial.end() if serial else m.end() + resp
        while not text[end - 1].isalnum():
            end -= 1
        picked = pick(by_name[key], _near_date(text, m.start(), end),
                      judgment_key="j")
        if picked is None:
            continue
        start = max(0, m.start() - APPLICANT_WINDOW) + cut
        while not text[start].isalnum():
            start += 1
        out.append((start, end, base + ECHR_LOCAL + picked[2]))
        consumed = end
    return out


def spans(text, base="https://lagen.nu/"):
    """Every resolvable ECHR citation in `text` as (start, end, uri),
    application numbers first -- the number is the stronger identity, so a
    name span overlapping one yields to it (the caller merges with its
    grammar refs the same way, via lagrum.yield_overlaps)."""
    by_name, by_no, respondents_sv = _index()
    numbered = _appno_refs(text, base, by_no)
    named = [s for s in _name_refs(text, base, by_name, respondents_sv)
             if not any(s[0] < e and n_s < s[1] for n_s, e, _ in numbered)]
    return sorted(numbered + named)


def refs(text, base, predicate, orig):
    """The `spans` projection as inline `lagrum.Ref`s, the way `treatyref.refs`
    and `malnummer.refs` hand their spans to the merge. Each link's own words
    are sliced from `orig` (see `lagrum.spans_as_refs`)."""
    return lagrum.spans_as_refs(spans(text, base), orig, predicate)
